### ISSUE TITLE
Pihole on another Pi works - Pihole as an addon in HA doesn't

### ISSUE THREAD

**Issue by h4nc** [hassio-addons/addon-pi-hole#61]
Currently I have my hassio and pihole systems running on two separate pi’s.

I had and have problems running both on one device.
Lately my pi zero w with pihole running made some problems. I had to unplug it to make it work again.
Also my hassio runs on a raspi connected via ethernet (so this might my slightly faster and more reliable)
The main reason why I had to set this up, is because my router does not support nat loopback.
So I first used dnsmasq and than switched to pihole (because of its benefits).

Now I’d like to “merge” both systems to use only one ethernet connected device. So I installed the pihole addon on my hassio. (So I turned off my pi zero, changed the dns in my router to the ip of my hassio)
My setup looks the same like tod36 posted here (https://community.home-assistant.io/t/community-hass-io-add-on-pi-hole/33817/341?u=h4nc), but I’m facing issues with some components. Components like netamo, alexa-mediaplayer and some else don’t get connected. There is however an internet connection, because my ping sensor und Aqara componet work.

I get some errors, most about failing SSL handshakes.
I think this might be the problem (copied from one of the errors).

ssl.CertificateError: hostname 'localhost' doesn't match ‚XXXXXX.duckdns.org'

How can I solve this issue?

EDIT:

After commenting out the pihole-sensor the ssl errors are gone.

But still most of my components can’t connect. This is one example (tado):

Error during setup of component tado
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/tado.py", line 47, in setup
    tado = Tado(username, password)
  File "/usr/local/lib/python3.6/site-packages/PyTado/interface.py", line 292, in __init__
    self._loginV2(username, password)
  File "/usr/local/lib/python3.6/site-packages/PyTado/interface.py", line 154, in _loginV2
    response = self.opener.open(req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again> 

I hope someone is able to help.
So in conclusion, using to pi's one running ha and one pihole everything works fine. Using the addon doesn't work for me.

<blockquote><img src="https://community.home-assistant.io/letter_avatar_proxy/v2/letter/t/f475e1/200.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-pi-hole/33817/341?u=h4nc">Community Hass.io Add-on: Pi-hole</a></strong></div><div>I’ve been stuck with 1 issue and it has to do with sensor information.  Unable to fetch data from Pi-hole 3:20 PM components/sensor/pi_hole.py (ERROR)  Can not load data from *hole: localhost:4865 3:20 PM util/async_.py (ERROR)  Here’s my sensor initialization in config.yaml  # Sensors sensor:   - platform: pi_hole     host: localhost:4865     monitored_conditions:       - ads_blocked_today       - dns_queries_today       - unique_clients     ssl: true  I’ve tried every host possible from all th...</div></blockquote>

**Comment by h4nc** [comment]
Running hassio
home assistant 0.85.1

**Comment by theBrozilla** [comment]
I have the same problem, my setup is as follows:
RPi 3B+
Current Home assistant version: Hassio 0.85.1
Last known working version: Hassio 0.84.6
Pi-hole addon version: 2.1.1
Let's encrypt 2.1.1

My HA cloud is stuck on connecting, media player is unable to fetch album pictures and darksky weather addon is unable to fetch new data. My logs are identical to h4nc's, with addition of media player errors:

`Wed Jan 16 2019 14:18:44 GMT+0100 (Central European Standard Time)

Error handling message: {'type': 'media_player_thumbnail', 'entity_id': 'media_player.living_room_speaker', 'id': 18}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 933, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 803, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/resolver.py", line 31, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "uvloop/loop.pyx", line 1459, in getaddrinfo
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/websocket_api/decorators.py", line 17, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 881, in websocket_handle_thumbnail
    data, content_type = await player.async_get_media_image()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 388, in async_get_media_image
    return await _async_fetch_image(self.hass, url)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 815, in _async_fetch_image
    response = await websession.get(url)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 403, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 500, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 832, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 937, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lh3.ggpht.com:80 ssl:None [Try again]`

**Comment by frenck** [comment]
@h4nc @theBrozilla 

Did you configure a **static IP** and **static external DNS** servers on the device running Hass.io?

**Comment by h4nc** [comment]
> static IP

yes

> static external DNS

Probably not. Don't know how to do that. 
In the Router UI DNS-field I set the IP of the device running Hass.io

**Comment by h4nc** [comment]
You a right, I thought reserving the IP in the router is the same as setting a static IP.

So after setting up a static ip and a static external it should work?

The DNS address filed within the router UI has to be set to the IP of the hass.io device, right?

**Comment by frenck** [comment]
@h4nc Please consult the Hass.io documentation and support forms/discord chats for those general kinds of questions. Thanks 👍

**Comment by theBrozilla** [comment]
@frenck
I had both reserved address on my DHCP and static on hass.io
Problem was that hass.io didn’t apply network settings from usb until host was rebooted. I assumed it did because everything was working fine for weeks until I upgraded home assistant to 0.85.1. 
Anyway, everything is ok, sorry for raising an issue before double checking.

**Comment by h4nc** [comment]
@theBrozilla 
I am still trying to work this out. 

I followed this [guide]( https://community.home-assistant.io/t/how-to-set-a-static-ip-on-hass-io-hassos/75680?u=h4nc) to setup a static ip. I still don't know if it worked and if I have a static IP now. Could you help?

What do you mean by "reserved both addresses"? I only reserved the ip address.

**Comment by theBrozilla** [comment]
Sure, but this is not the place, issue is resolved. Please create a topic on home assistant community, hass.io subforum and someone will help you, I follow the community myself:

https://community.home-assistant.io/c/hass-io

**Comment by h4nc** [comment]
Thanks:

https://community.home-assistant.io/t/hass-io-static-ip-and-other-network-regarding-questions/92366
